name: Build APK
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Install Android SDK tools
        uses: android-actions/setup-android@v3
      - name: Accept SDK licenses
        run: yes | sdkmanager --licenses
      - name: Install Gradle 8.6
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip
          wget https://services.gradle.org/distributions/gradle-8.6-bin.zip -O gradle-8.6-bin.zip
          unzip -q gradle-8.6-bin.zip -d $HOME
          echo "$HOME/gradle-8.6/bin" >> $GITHUB_PATH
          gradle --version
      - name: Generate debug keystore
        run: |
          mkdir -p ~/.android
          keytool -genkey -v -keystore ~/.android/debug.keystore             -storepass android -alias androiddebugkey -keypass android             -keyalg RSA -keysize 2048 -validity 10000             -dname "CN=Android Debug,O=Android,C=US"
      - name: Build Debug APK
        run: gradle clean :app:assembleDebug
      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: app/build/outputs/apk/debug/*.apk
